/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const entities: typeof import('@entities/index.js')['entities']
  const getImageUrl: typeof import('@utils/ImageManager.js')['getImageUrl']
  const templates: typeof import('@templates/index.js')['templates']
  const types: typeof import('@utils/types.js')['default']
}
